<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Entity</AssemblyName>
    <RootNamespace>Fantasy</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Fantasy-Net" Version="$(FantasyNetVersion)" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.2" />
  </ItemGroup>

</Project>
