using Fantasy.Entitas;
using Microsoft.IdentityModel.Tokens;


public class GateJwtComponent : Entity
{
    public string PublicKeyPem = "MIIBCgKCAQEAqc1moV1nynBYVXhsXeTuDc/DcC7TSQ+dVmTsyeUZP+PaiZjxp/cIo0sj9OCAcAK2nCBpIjBjM7Rbg7Uslb4KvlH8eshsH8LOL9KybNsB0uFg/kPvSvIBcdWsxbbARxDGrTl+Nh1t6s2V1voK9g+OQqK/xIyhvrwFYIjc1/O6FI4uGyMag3D6MJATW2SCrwe1tKU9dfk72VrIqT4FVzbZUDQdFxEKHiQ4vcoBiGxsoYWr6lxbrrtDDNzPzVEgzDbsvaPvSCNRacFaBCJBeGCWGn/fKKBOl5NV2EfXa8oNFgw0VfC4JiRpPUjdhsKvzjtp5P3AYrnloGkTxp9HLkdDjwIDAQAB";
    public SigningCredentials SigningCredentials;
    public TokenValidationParameters TokenValidationParameters;
}

